A neural network is a model tmimics the workings of a human brain. It goes through a series of "thoughts" to recognize and analyze patterns. It can be organized as a flow chart. 

the general steps to building a neural network are: 
- defining the structure of the model
- adding a line that tells the children of the model which parents to call
- applying an activation function
- creating an instance of the model
- defining the loss function and optimizer
- minimizing the loss function using either forward or back propagation

you generally check the performance of a neural network with cross entropy. This is because the model is looking for patterns and classifying the data based on those patterns.

In [1]:
import pandas as pd

credit_df = pd.read_csv('Credit_card.csv')
credit_df.head()

,Ind_ID,GENDER,Car_Owner,Propert_Owner,CHILDREN,Annual_income,Type_Income,EDUCATION,Marital_status,Housing_type,Birthday_count,Employed_days,Mobile_phone,Work_Phone,Phone,EMAIL_ID,Type_Occupation,Family_Members
0,5008827,M,Y,Y,0,180000.0,Pensioner,Higher education,Married,House / apartment,-18772.0,365243,1,0,0,0,NaN,2
1,5009744,F,Y,N,0,315000.0,Commercial associate,Higher education,Married,House / apartment,-13557.0,-586,1,1,1,0,NaN,2
2,5009746,F,Y,N,0,315000.0,Commercial associate,Higher education,Married,House / apartment,NaN,-586,1,1,1,0,NaN,2
3,5009749,F,Y,N,0,NaN,Commercial associate,Higher education,Married,House / apartment,-13557.0,-586,1,1,1,0,NaN,2
4,5009752,F,Y,N,0,315000.0,Commercial associate,Higher education,Married,House / apartment,-13557.0,-586,1,1,1,0,NaN,2

In [2]:
credit_df.columns

Index(['Ind_ID', 'GENDER', 'Car_Owner', 'Propert_Owner', 'CHILDREN',
       'Annual_income', 'Type_Income', 'EDUCATION', 'Marital_status',
       'Housing_type', 'Birthday_count', 'Employed_days', 'Mobile_phone',
       'Work_Phone', 'Phone', 'EMAIL_ID', 'Type_Occupation', 'Family_Members'],
      dtype='str')

In [3]:
from sklearn.preprocessing import LabelEncoder

class_labels = LabelEncoder()
credit_df['Gender'] = class_labels.fit_transform(credit_df['GENDER'].values)
credit_df['Car?'] = class_labels.fit_transform(credit_df['Car_Owner'].values)
credit_df['Property?'] = class_labels.fit_transform(credit_df['Propert_Owner'].values)
credit_df['Income_Type'] = class_labels.fit_transform(credit_df['Type_Income'].values)
credit_df['Education'] = class_labels.fit_transform(credit_df['EDUCATION'].values)
credit_df['Relationship_Status'] = class_labels.fit_transform(credit_df['Marital_status'].values)
credit_df['Housing'] = class_labels.fit_transform(credit_df['Housing_type'].values)
credit_df

,Ind_ID,GENDER,Car_Owner,Propert_Owner,CHILDREN,Annual_income,Type_Income,EDUCATION,Marital_status,Housing_type,...,EMAIL_ID,Type_Occupation,Family_Members,Gender,Car?,Property?,Income_Type,Education,Relationship_Status,Housing
0,5008827,M,Y,Y,0,180000.0,Pensioner,Higher education,Married,House / apartment,...,0,NaN,2,1,1,1,1,1,1,1
1,5009744,F,Y,N,0,315000.0,Commercial associate,Higher education,Married,House / apartment,...,0,NaN,2,0,1,0,0,1,1,1
2,5009746,F,Y,N,0,315000.0,Commercial associate,Higher education,Married,House / apartment,...,0,NaN,2,0,1,0,0,1,1,1
3,5009749,F,Y,N,0,NaN,Commercial associate,Higher education,Married,House / apartment,...,0,NaN,2,0,1,0,0,1,1,1
4,5009752,F,Y,N,0,315000.0,Commercial associate,Higher education,Married,House / apartment,...,0,NaN,2,0,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1543,5028645,F,N,Y,0,NaN,Commercial associate,Higher education,Married,House / apartment,...,0,Managers,2,0,0,1,0,1,1,1
1544,5023655,F,N,N,0,225000.0,Commercial associate,Incomplete higher,Single / not married,House / apartment,...,0,Accountants,1,0,0,0,0,2,3,1
1545,5115992,M,Y,Y,2,180000.0,Working,Higher education,Married,House / apartment,...,0,Managers,4,1,1,1,3,1,1,1
1546,5118219,M,Y,N,0,270000.0,Working,Secondary / secondary special,Civil marriage,House / apartment,...,0,Drivers,2,1,1,0,3,4,0,1
1547,5053790,F,Y,Y,0,225000.0,Working,Higher education,Married,House / apartment,...,0,NaN,2,0,1,1,3,1,1,1

In [4]:
credit_df = credit_df[['Ind_ID', 'CHILDREN', 'Annual_income', 'Birthday_count', 'Employed_days', 'Mobile_phone',
       'Work_Phone', 'Phone', 'EMAIL_ID', 'Family_Members', 'Gender', 'Car?', 'Property?', 'Income_Type', 
       'Education', 'Relationship_Status', 'Housing']]
credit_df

,Ind_ID,CHILDREN,Annual_income,Birthday_count,Employed_days,Mobile_phone,Work_Phone,Phone,EMAIL_ID,Family_Members,Gender,Car?,Property?,Income_Type,Education,Relationship_Status,Housing
0,5008827,0,180000.0,-18772.0,365243,1,0,0,0,2,1,1,1,1,1,1,1
1,5009744,0,315000.0,-13557.0,-586,1,1,1,0,2,0,1,0,0,1,1,1
2,5009746,0,315000.0,NaN,-586,1,1,1,0,2,0,1,0,0,1,1,1
3,5009749,0,NaN,-13557.0,-586,1,1,1,0,2,0,1,0,0,1,1,1
4,5009752,0,315000.0,-13557.0,-586,1,1,1,0,2,0,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1543,5028645,0,NaN,-11957.0,-2182,1,0,0,0,2,0,0,1,0,1,1,1
1544,5023655,0,225000.0,-10229.0,-1209,1,0,0,0,1,0,0,0,0,2,3,1
1545,5115992,2,180000.0,-13174.0,-2477,1,0,0,0,4,1,1,1,3,1,1,1
1546,5118219,0,270000.0,-15292.0,-645,1,1,1,0,2,1,1,0,3,4,0,1
1547,5053790,0,225000.0,-16601.0,-2859,1,0,0,0,2,0,1,1,3,1,1,1

In [5]:
credit_df = credit_df.dropna()
credit_df = credit_df.drop_duplicates()
credit_df

,Ind_ID,CHILDREN,Annual_income,Birthday_count,Employed_days,Mobile_phone,Work_Phone,Phone,EMAIL_ID,Family_Members,Gender,Car?,Property?,Income_Type,Education,Relationship_Status,Housing
0,5008827,0,180000.0,-18772.0,365243,1,0,0,0,2,1,1,1,1,1,1,1
1,5009744,0,315000.0,-13557.0,-586,1,1,1,0,2,0,1,0,0,1,1,1
4,5009752,0,315000.0,-13557.0,-586,1,1,1,0,2,0,1,0,0,1,1,1
5,5009753,0,315000.0,-13557.0,-586,1,1,1,0,2,2,1,0,1,1,1,1
6,5009754,0,315000.0,-13557.0,-586,1,1,1,0,2,0,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1542,5118268,1,360000.0,-11294.0,-3536,1,0,1,0,3,1,1,0,2,4,1,1
1544,5023655,0,225000.0,-10229.0,-1209,1,0,0,0,1,0,0,0,0,2,3,1
1545,5115992,2,180000.0,-13174.0,-2477,1,0,0,0,4,1,1,1,3,1,1,1
1546,5118219,0,270000.0,-15292.0,-645,1,1,1,0,2,1,1,0,3,4,0,1
1547,5053790,0,225000.0,-16601.0,-2859,1,0,0,0,2,0,1,1,3,1,1,1

In [6]:
#does education impact income type?
credit_df['Income_Type'].to_numpy()

import torch
from sklearn.model_selection import train_test_split
X = credit_df.drop('Income_Type', axis = 1).values
y = credit_df['Income_Type']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, stratify = y)

In [7]:
import torch.nn as nn
import torch.nn.functional as F 
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

print(X_train)

#not really sure what happened here, but i kept going

ValueError: could not determine the shape of object type 'Series'

In [ ]:
class ANN_Model(nn.Module):
    def __init__(self, input_features=8, 
                 hidden1=20, hidden2=20, 
                 out_features=2):
        super().__init__()
        self.layer_1_connection = nn.Linear(input_features, hidden1)
        self.layer_2_connection = nn.Linear(hidden1, hidden2)
        self.out = nn.Linear(hidden2, out_features)

    def forward(self, x):
        x = F.relu(self.layer_1_connection(x))
        x = F.relu(self.layer_2_connection(x))
        x = self.out(x)
        return x

In [ ]:
torch.manual_seed(50)
ann=ANN_Model()

In [ ]:
loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(ann.parameters(), lr = 0.01)

In [ ]:
final_loss = []
n_epochs = 500
for epoch in range(n_epochs):
    y_pred = ann.forward(X_train)
    loss = loss_function(y_pred, y_train)
    final_loss.append(loss)

    if epoch % 10 == 1:
        print(f'Epoch number: {epoch} with loss {loss}')

    optimizer.zero_grad() 
    loss.backward()
    optimizer.step()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1052x16 and 8x20)

Due to the errors, i am unable to tell if a neural network would perform better or worse than other models i have created. However, i would expect the neural network to do better, since it is much more complex than any model i've created before. it can recognize patterns easier than most other machine learning models, so it would probably perform better overall.